# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cpU2dKFXpRAiujp-Dt9KqBcK3HRQpm7T
"""

#Depending on where you run it us "os" or the "IPython.display"
from time import sleep
from IPython.display import clear_output
#import os

#def clear_output():
#  os.system("cls")


#Formats the string into a list for better maths
def theformater(equation):
  equation = equation.replace(" ", "")
  teq = []
  iteration = 1
  tempstr = ""
  #This for is so that if a number has multiple digits it isn't set into a
  #different place inside the list
  for nos in equation:
    if nos.isdigit() or nos == ".":
      if iteration == len(equation):
        teq.append(tempstr+nos)
        break
      tempstr += nos
    else:
      if nos == "^":
        nos = "**"
      teq.append(tempstr)
      teq.append(nos)
      tempstr = ""
    iteration += 1
  if "" in teq:
    teq.pop(teq.index(""))
  return teq

def operator(feq, symbol):
  operator = feq.count(symbol)
  ignore = 0
  for i in range (operator):
    i = feq.index(symbol)
    match symbol:
      case "+":
        if i == 0:
          result = float(feq[i+1])
          ignore = 1
        else:
          result = float(feq[i-1])+float(feq[i+1])
      case "**":
        result = float(feq[i-1])**float(feq[i+1])
      case "*":
        result = float(feq[i-1])*float(feq[i+1])
      case "/":
        result = float(feq[i-1])/float(feq[i+1])
      case "-":
        if i == 0:
          feq[i+1] = -float(feq[i+1])
          ignore = 1
        else:
          result = float(feq[i-1])-float(feq[i+1])
    if ignore == 0:
      for h in range(3):
        feq.pop(i-1)
      feq.insert(i-1, result)
    elif ignore == 1:
      feq.pop(i)
  if len(feq) == 1:
    return str(feq[0])
  else:
    return feq


##CALCULATOR v3.0
sleep(0.5)
print("-"*30)
sleep(0.5)
print("Welcome to Calculator 3.0")
sleep(0.5)
print("-"*30)
sleep(2)
clear_output()
sleep(0.2)
print("Insert your equation (No algebra):")
while True:
  eq = input().lower()
  if("+" in eq or "-" in eq or "*" in eq or "^" in eq or "/" in eq):
    q = theformater(eq)
    while "+" in q or "-" in q or "*" in q or "^" in q or "/" in q or "**" in q:
      if "**" in q:
        q = operator(q, "**")
      elif "/" in q:
        q = operator(q, "/")
      elif "*" in q:
        q = operator(q, "*")
      elif "-" in q:
        q = operator(q, "-")
      elif "+" in q:
        q = operator(q, "+")
    print("The result of your equation is:\n"+str(q)+"\nYou may enter another one:")
  elif eq == "exit":
    print("Exiting!")
    break